### ISSUE TITLE
Error installing new package

### ISSUE THREAD

**Issue by blackchineykh** [minhlucvan/n8n-nodes-browserless#12]
Error loading package "n8n-nodes-browserless" :The specified package could not be loaded Cause: Class extends value undefined is not a constructor or null

n8n Version 1.61.0

**Comment by minhlucvan** [comment]
Hi @blackchineykh, could you share more logs, I am able to run the node with `n8n@1.62.3`

**Comment by att083** [comment]
same issue here, I installed n8n via https://github.com/n8n-io/self-hosted-ai-starter-kit. using docker desktop. The version I use is 1.62.4

2024-10-11 16:44:12 Error loading node "Browserless" from: "/home/node/.n8n/nodes/node_modules/n8n-nodes-browserless/dist/nodes/Browserless/Browserless.node.js" - Class extends value undefined is not a constructor or null
2024-10-11 16:44:13 InternalServerError: Error loading package "n8n-nodes-browserless" :The specified package could not be loaded
2024-10-11 16:44:13 Cause: Class extends value undefined is not a constructor or null

**Comment by minhlucvan** [comment]
Hi @att083 , did you install the node from GUI 
![image](https://github.com/user-attachments/assets/8f1c6797-b391-4c6d-a875-f158803c1c3c)

**Comment by minhlucvan** [comment]
btw, I have another node that kind of similar to browserless called firecrawl

https://community.n8n.io/t/n8n-community-node-firecrawl/55546

you might want to check it out while reolving the issue

**Comment by blackchineykh** [comment]
> Hi @blackchineykh, could you share more logs, I am able to run the node with `n8n@1.62.3`

Here are the logs I see. I am installing from the GUI

```
Error loading node "Browserless" from: "/home/node/.n8n/nodes/node_modules/n8n-nodes-browserless/dist/nodes/Browserless/Browserless.node.js" - Class extends value undefined is not a constructor or null
InternalServerError: Error loading package "n8n-nodes-browserless" :The specified package could not be loaded
Cause: Class extends value undefined is not a constructor or null
Error loading node "Browserless" from: "/home/node/.n8n/nodes/node_modules/n8n-nodes-browserless/dist/nodes/Browserless/Browserless.node.js" - Class extends value undefined is not a constructor or null
InternalServerError: Error loading package "n8n-nodes-browserless" :The specified package could not be loaded
Cause: Class extends value undefined is not a constructor or null
browserId check failed on /rest/community-packages/
```

**Comment by Zewb** [comment]
Hey @minhlucvan  same issue as the other person. 

```
Error installing new package
Error loading package "n8n-nodes-browserless" :The specified package could not be loaded Cause: Class extends value undefined is not a constructor or null
```

**Comment by SvbZ3r0** [comment]
```js
Error loading package "n8n-nodes-browserless" :The specified package could not be loaded
Cause: Class could not be found. Please check if the class is named correctly.
ResponseError: Error loading package "n8n-nodes-browserless" :The specified package could not be loaded
Cause: Class could not be found. Please check if the class is named correctly.
    at CommunityPackagesController.installPackage (/usr/local/lib/node_modules/n8n/dist/controllers/community-packages.controller.js:81:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at handler (/usr/local/lib/node_modules/n8n/dist/decorators/controller.registry.js:93:24)
    at /usr/local/lib/node_modules/n8n/dist/response-helper.js:110:26
```
I faced a similar issue trying to install this from the GUI. Running n8n docker on unRaid.

**Comment by GollyJer** [comment]
> Error loading package "n8n-nodes-browserless" :The specified package could not be loaded
> Cause: Class could not be found. Please check if the class is named correctly.
> ResponseError: Error loading package "n8n-nodes-browserless" :The specified package could not be loaded
> Cause: Class could not be found. Please check if the class is named correctly.
>     at CommunityPackagesController.installPackage (/usr/local/lib/node_modules/n8n/dist/controllers/community-packages.controller.js:81:19)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at handler (/usr/local/lib/node_modules/n8n/dist/decorators/controller.registry.js:93:24)
>     at /usr/local/lib/node_modules/n8n/dist/response-helper.js:110:26
> 
> I faced a similar issue trying to install this from the GUI. Running n8n docker on unRaid.

Any luck getting this working @SvbZ3r0?  
I'm also using unraid and facing the same issue. I haven't had trouble installing any other community nodes.

**Comment by SvbZ3r0** [comment]
Nope. I ended up using a completely different product for my issue.

**Comment by GollyJer** [comment]
> Nope. I ended up using a completely different product for my issue.

Hey @SvbZ3r0 thanks for the response.
Did you end up with something else that worked in n8n, or not using n8n at all. Just curious. Thanks!

**Comment by SvbZ3r0** [comment]
Didn't use n8n at all. I tried Scraperr, and while it was powerful, it wasn't exactly intutive. I ended up using a good Windows based tool called Octoparse.

**Comment by sbc** [comment]
I'm also unable to get this plugin working. I'm on n8n 1.77.3.

Installed via the web. Getting the following in the UI when testing a node:

> Problem running workflow
> Unrecognized node type: browserless.undefined

Seeing the following in the logs:

> 2025-03-02T21:08:32.990215777Z app[web.1]: Unrecognized node type: browserless.undefined
> 2025-03-02T21:08:32.990260112Z app[web.1]: Error: Unrecognized node type: browserless.undefined
> 2025-03-02T21:08:32.990263649Z app[web.1]:     at LoadNodesAndCredentials.getNode (/usr/local/lib/node_modules/n8n/dist/load-nodes-and-credentials.js:285:19)
> 2025-03-02T21:08:32.990266656Z app[web.1]:     at NodeTypes.getByNameAndVersion (/usr/local/lib/node_modules/n8n/dist/node-types.js:36:51)
> 2025-03-02T21:08:32.990269581Z app[web.1]:     at new Workflow (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:56:39)
> 2025-03-02T21:08:32.990272467Z app[web.1]:     at TestWebhooks.toWorkflow (/usr/local/lib/node_modules/n8n/dist/webhooks/test-webhooks.js:290:16)
> 2025-03-02T21:08:32.990275292Z app[web.1]:     at TestWebhooks.needsWebhook (/usr/local/lib/node_modules/n8n/dist/webhooks/test-webhooks.js:169:31)
> 2025-03-02T21:08:32.990278107Z app[web.1]:     at WorkflowExecutionService.executeManually (/usr/local/lib/node_modules/n8n/dist/workflows/workflow-execution.service.js:114:58)
> 2025-03-02T21:08:32.990281003Z app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> 2025-03-02T21:08:32.990283758Z app[web.1]:     at WorkflowsController.runManually (/usr/local/lib/node_modules/n8n/dist/workflows/workflows.controller.js:293:16)
> 2025-03-02T21:08:32.990286594Z app[web.1]:     at handler (/usr/local/lib/node_modules/n8n/dist/decorators/controller.registry.js:93:24)
> 2025-03-02T21:08:32.990289379Z app[web.1]:     at /usr/local/lib/node_modules/n8n/dist/response-helper.js:110:26

**Comment by sbc** [comment]
> I'm also unable to get this plugin working. I'm on n8n 1.77.3.

In my case it ended up being a permissions error in my n8n directory. I followed the instructions for manual installation and that got it squared away.

**Comment by ljohnso16** [comment]
@sbc what permission? I installed via docker still have the same error when installing

**Comment by sbc** [comment]
In my case I had my n8n directory (/home/node/.n8n) mounted via docker but it was owned by the wrong user. I needed to use `chown -R 1000:1000` to change ownership to the dokku user. Then I was able to manually install the node by following these steps:

https://docs.n8n.io/integrations/community-nodes/installation/manual-install/

**Comment by cdxiaodong** [comment]
so do i
Error loading package "n8n-nodes-wechat-offiaccount" :The specified package could not be loaded Cause: Class could not be found. Please check if the class is named correctly.

version：1.89.2 / 1.90.2


but it does success in  another clean machine  version:1.85.4
